name: test

on: [push, pull_request]

jobs:
  run_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: 'zulu'

      - name: Run test
        run: mvn -pl . test -Dtest='uk.gov.gchq.gaffer.commonutil.OneOrMoreTest.shouldAddAllItemsWithDeduplicate#core/common-util'

  run_nondex_test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        java-version: 8
        distribution: 'zulu'

    - name: Run nondex test
      run: mvn -pl . edu.illinois:nondex-maven-plugin:1.1.2:nondex -Dtest='uk.gov.gchq.gaffer.commonutil.OneOrMoreTest.shouldAddAllItemsWithDeduplicate#core/common-util'
